<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Iniciar Sesión</title>
    @vite('resources/css/app.css')
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.15.0/dist/cdn.min.js"></script>
</head>
<body class="w-screen h-screen bg-verde-azulado print:text-sm print:bg-white print:text-black">
    <x-app-navbar titulo="Lista de solicitantes"></x-app-navbar>
    <div role="region" aria-labelledby="Cap1" tabindex="0" class="w-5/6 lg:w-4/5 mx-auto flex flex-col pt-8 md:pt-12 print:m-0 font-roboto ">
        <table id="registros">
            <caption id="Cap1" class="text-lg pl-2 md:pl-0 md:ml-4 text-left md:text-center font-medium text-white print:text-black bg-azul-oscuro print:bg-transparent md:bg-transparent font-bold md:font-normal">Alumnos solicitantes de apoyo</caption>
            <tr class="hidden md:table-row print:border-b-2">
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">Apellido y Nombre</th>
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left md:text-right bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">CUD</th>
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">Email</th>
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left md:text-right bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">Teléfono</th>
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left md:text-right bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">Fecha Solicitud</th>
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left md:text-right bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">Última Modificación</th>
                <th class="py-1 pl-2 pr-4 align-text-bottom text-left bg-azul-oscuro print:bg-transparent text-white print:text-black font-bold">Ficha Académica</th>
            </tr>
            <tr class="print:!bg-transparent even:bg-azul-marino odd:bg-azul-marino-alterno print:border-b-1">
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Apellido_y_Nombre:_'] before:inline md:before:hidden print:bg-transparent">Gomez Pepe</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['CUD:_'] before:inline md:before:hidden print:bg-transparent">1111111111</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Email:_'] before:inline md:before:hidden print:bg-transparent">pepegomez2222@unsl.dev</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Teléfono:_'] before:inline md:before:hidden print:bg-transparent">2664000000</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Fecha_Solicitud:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Última_Modificación:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-center text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Ficha_Académica:_'] before:inline md:before:hidden print:bg-transparent"><a href="#" class="underline text-yellow-300 print:text-black hover:text-yellow-600">modificar</a></td>
            </tr>
            <tr class="print:!bg-transparent even:bg-azul-marino odd:bg-azul-marino-alterno print:border-b-1">
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Apellido_y_Nombre:_'] before:inline md:before:hidden print:bg-transparent">Gomez Pepe</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['CUD:_'] before:inline md:before:hidden print:bg-transparent">1111111111</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Email:_'] before:inline md:before:hidden print:bg-transparent">pepegomez2222@unsl.dev</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Teléfono:_'] before:inline md:before:hidden print:bg-transparent">2664000000</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Fecha_Solicitud:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Última_Modificación:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-center text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Ficha_Académica:_'] before:inline md:before:hidden print:bg-transparent"><a href="#" class="underline text-yellow-300 print:text-black hover:text-yellow-600">solicitud</a></td>
            </tr>
            <tr class="print:!bg-transparent even:bg-azul-marino odd:bg-azul-marino-alterno print:border-b-1">
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Apellido_y_Nombre:_'] before:inline md:before:hidden print:bg-transparent">Gomez Pepe</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['CUD:_'] before:inline md:before:hidden print:bg-transparent">1111111111</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Email:_'] before:inline md:before:hidden print:bg-transparent">pepegomez2222@unsl.dev</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Teléfono:_'] before:inline md:before:hidden print:bg-transparent">2664000000</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Fecha_Solicitud:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Última_Modificación:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-center text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Ficha_Académica:_'] before:inline md:before:hidden print:bg-transparent"><a href="#" class="underline text-yellow-300 print:text-black hover:text-yellow-600">solicitud</a></td>
            </tr>
            <tr class="print:!bg-transparent even:bg-azul-marino odd:bg-azul-marino-alterno print:border-b-1">
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Apellido_y_Nombre:_'] before:inline md:before:hidden print:bg-transparent">Gomez Pepe</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['CUD:_'] before:inline md:before:hidden print:bg-transparent">1111111111</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Email:_'] before:inline md:before:hidden print:bg-transparent">pepegomez2222@unsl.dev</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Teléfono:_'] before:inline md:before:hidden print:bg-transparent">2664000000</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Fecha_Solicitud:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Última_Modificación:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-center text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Ficha_Académica:_'] before:inline md:before:hidden print:bg-transparent"><a href="#" class="underline text-yellow-300 print:text-black hover:text-yellow-600">solicitud</a></td>
            </tr>
            <tr class="print:!bg-transparent even:bg-azul-marino odd:bg-azul-marino-alterno print:border-b-1">
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Apellido_y_Nombre:_'] before:inline md:before:hidden print:bg-transparent">Gomez Pepe</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['CUD:_'] before:inline md:before:hidden print:bg-transparent">1111111111</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Email:_'] before:inline md:before:hidden print:bg-transparent">pepegomez2222@unsl.dev</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Teléfono:_'] before:inline md:before:hidden print:bg-transparent">2664000000</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Fecha_Solicitud:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Última_Modificación:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-center text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Ficha_Académica:_'] before:inline md:before:hidden print:bg-transparent"><a href="#" class="underline text-yellow-300 print:text-black hover:text-yellow-600">solicitud</a></td>
            </tr>
            <tr class="print:!bg-transparent even:bg-azul-marino odd:bg-azul-marino-alterno print:border-b-1">
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Apellido_y_Nombre:_'] before:inline md:before:hidden print:bg-transparent">Gomez Pepe</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['CUD:_'] before:inline md:before:hidden print:bg-transparent">1111111111</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Email:_'] before:inline md:before:hidden print:bg-transparent">pepegomez2222@unsl.dev</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-right text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Teléfono:_'] before:inline md:before:hidden print:bg-transparent">2664000000</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Fecha_Solicitud:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-right before:text-left md:before:text-inherit text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Última_Modificación:_'] before:inline md:before:hidden print:bg-transparent">01/01/1900</td>
                <td class="py-1 pl-2 pr-4 align-text-bottom md:align-text-top text-left md:text-center text-white print:text-black grid grid-cols-[8em_auto] gap-y-[1em] gap-x-[0.5em] md:block md:table-cell before:font-bold before:content-['Ficha_Académica:_'] before:inline md:before:hidden print:bg-transparent"><a href="#" class="underline text-yellow-300 print:text-black hover:text-yellow-600">solicitud</a></td>
            </tr>
        </table>
    </div>
</body>
</html>